version: "2.1"

services:
  db:
    image: mysql:latest
    container_name: db
    hostname: db
    environment:
      - MYSQL_DATABASE=sample
      - MYSQL_USER=vega
      - MYSQL_PASSWORD=vega
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=vega --password=vega --execute \"SHOW DATABASES;\""
    networks:
      - red_puente

  app:
    image: dockerjava
    depends_on:
      db:
       condition: service_healthy
    container_name: app
    hostname: app
    ports:
      - 8080:8080 # application
      - 9990:9990 # admin console
    networks:
      - red_puente

  angular:
    image: dockerangular 
    container_name: ag
    hostname: ag
    ports:
     - 4200:4200
    networks:
     - red_puente

networks:
    red_puente:
        driver: bridge